// The Script to add ERF responses to the district directory! 
// 
// Instructions: 
// 
// This script should be attached to the ERF responses spreadsheet and run from there. It will append the data from that sheet into
// the directory in a properly formatted fashion.

function addToDirectory() {
  // The constants are added inside the function because Google did a poor job of their Javascript implementation...
  
  // ************************************************************* CONSTANTS **********************************************************************
  
  // The key of the district directory file. This can be obtained from the URL of the directory file. 
  const DIRECTORY_FILE_KEY = "1PIi91UNZma2eLBzy9r8jInI33k1pmyalqDie0TskVRY";
  // The key of the club master list. This can be obtained from the URL of the directory file.
  const CLUB_LIST_KEY = "1ampGmld42vL5xVv-zy9HBxzdeFF-0RZMDq6SS276iTw";
  // This is the name of the sheet that you want to append the submitted values to. Should be RAW unless changed for some reason.
  const DIRECTORY_FILE_SHEET_NAME = "RAW";
  // This is the name of the sheet that we want to take form responses from. It should be generated by the ERF form.
  const RESPONSES_FILE_SHEET_NAME = "Form Responses 1"
  
  // This is the column in which the college names are found.
  const COLLEGE = 3;
  // The column of the president's name
  const PRES_NAME = 7;
  // The column of the president's email
  const PRES_EMAIL = 8;
   
  // **********************************************************************************************************************************************
  // A dictionary that has all of the different clubs
  var club_dict = {};
  
  // Get the responses spreadsheet. It should be the active sheet assuming this was run from a sheets project.
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var response_sheet = spreadsheet.getSheetByName(RESPONSES_FILE_SHEET_NAME);
  var responses = response_sheet.getDataRange().getValues();
  
  // Parse all of the club names and their Divisions!
  var club_spreadsheet = SpreadsheetApp.openById(CLUB_LIST_KEY);
  var clubs = club_spreadsheet.getDataRange().getValues();
  //Logger.log(clubs[4][7]);
  var i = 0;
  var j = 1;
  while ( !clubs[0][i].equals("")) {
    while (!clubs[j][i].equals("")) {
      var club = clubs[j][i];
      Logger.log(clubs[j][i]);
      j++;
    }
    j = 1;
    i++;
  }
  
  var current_college, hh;
  for (var i = 1; i < responses.length; i++) {
    
  
    //Logger.log(responses[i][PRES_NAME]);
  }
  
  
  
  spreadsheet = SpreadsheetApp.openById(DIRECTORY_FILE_KEY);
  SpreadsheetApp.setActiveSpreadsheet(spreadsheet);
  sheet = spreadsheet.getSheetByName(DIRECTORY_FILE_SHEET_NAME);

  
}
